---
- name: Create RDMO config
  become: yes
  become_user: "{{ rdmo_user }}"
  template:
    src: sample.local.py
    dest: "{{ rdmo_conf_dir }}/local.py"
    mode: '0600'

- name: Copy RDMO systemd unit files
  template:
    src: rdmo.service.j2
    dest: "/etc/systemd/system/{{ rdmo_user }}.service"

