---
- name: manage.py import catalogs
  become: yes
  become_user: "{{ rdmo_user }}"
  django_manage:
    command: "{{ item }}"
    app_path: "{{ rdmo_app_dir }}"
    virtualenv: "{{ rdmo_env_dir }}"
  with_items:
    - "import {{ rdmo_home }}/rdmo-catalogs/rdmorganiser/domain/rdmo.xml"
    - "import {{ rdmo_home }}/rdmo-catalogs/rdmorganiser/conditions/rdmo.xml"
    - "import {{ rdmo_home }}/rdmo-catalogs/rdmorganiser/options/rdmo.xml"
    - "import {{ rdmo_home }}/rdmo-catalogs/rdmorganiser/conditions/rdmo.xml"

    - "import {{ rdmo_home }}/rdmo-catalogs/rdmorganiser/questions/ua_ruhr.xml"
    - "import {{ rdmo_home }}/rdmo-catalogs/rdmorganiser/questions/consultation.xml"
    - "import {{ rdmo_home }}/rdmo-catalogs/rdmorganiser/questions/proposal.xml"
    - "import {{ rdmo_home }}/rdmo-catalogs/rdmorganiser/questions/archive.xml"
    - "import {{ rdmo_home }}/rdmo-catalogs/rdmorganiser/questions/rdmo.xml"

    - "import {{ rdmo_home }}/rdmo-catalogs/rdmorganiser/tasks/rdmo.xml"
    - "import {{ rdmo_home }}/rdmo-catalogs/rdmorganiser/views/rdmo.xml"

