---
- name: Install Python 3 virtualenv
  package:
    name: ['virtualenv', 'python3-virtualenv', 'python3-setuptools', 'python3-venv']
    state: latest

- name: Install RDMO dependencies
  package:
    name: ['build-essential', 'libxml2-dev', 'libxslt-dev', 'zlib1g-dev', 'python3-dev', 'python3-pip', 'git', 'pandoc']
    state: latest

- name: Install optional RDMO dependencies
  package:
    name: ['texlive', 'texlive-xetex']
    state: latest

- name: Install Memcached
  package:
    name: 'memcached'
    state: latest

- name: Install PostgreSQL dependencies
  package:
    name: ['postgresql-common', 'postgresql-server-dev-all', 'libpq-dev']
    state: latest

- name: Install LDAP dependencies
  package:
    name: ['libsasl2-dev', 'libldap2-dev', 'libssl-dev']
    state: latest

