---
- name: Install PostgreSQL
  package:
    name: ['postgresql']

- name: Make sure postgresql-common and psycopg2 are installed
  package:
    name: ['postgresql-common', 'python3-psycopg2']
    state: latest

- name: Read (slurp) existing ~/.pgpass for RDMO user if available
  ansible.builtin.slurp:
    src: "{{ rdmo_home }}/.pgpass"
  register: pgpass_content_b64encoded
  ignore_errors: yes

- name: Set ansible fact with PostgreSQL rdmo user password
  set_fact:
    rdmo_postgres_password: "{{ pgpass_content_b64encoded['content'] | default('') | b64decode | regex_findall('localhost::' + rdmo_user + ':' + rdmo_user + ':(.+)') | first | default(lookup('password', '/dev/null chars=ascii_lowercase,ascii_uppercase,digits length=8 length=64')) }}"

- name: "Debug: show postgres password"
  debug:
    msg: "Debug: rdmo postgres password: {{ rdmo_postgres_password }}"

- name: Create RDMO user
  become: yes
  become_user: "postgres"
  postgresql_user:
    name: "{{ rdmo_postgres_user }}"
    password: "{{ rdmo_postgres_password }}"
    encrypted: yes

- name: Create RDMO database
  become: yes
  become_user: "postgres"
  postgresql_db:
    name: "{{ rdmo_postgres_user }}"
    state: present
    owner: "{{ rdmo_postgres_user }}"

