---
- name: Make sure postgresql-client and psycopg2 are installed
  package:
    name: ['postgresql-client', 'python3-psycopg2']
    state: latest

- name: Create RDMO user
  postgresql_user:
    login_host: "{{ pgserver }}"
    login_password: "{{ pgpassword }}"
    name: "{{ rdmo_postgres_user }}"
    password: "{{ rdmo_postgres_password }}"
    encrypted: yes

- name: Create RDMO database
  postgresql_db:
    login_host: "{{ pgserver }}"
    login_password: "{{ pgpassword }}"
    name: "{{ rdmo_postgres_user }}"
    state: present
    owner: "{{ rdmo_postgres_user }}"

